DATALOADER:
  NUM_WORKERS: 0
DATASET:
  AUGMENTATION:
    FLIPS: true
  MODALITIES:
    3D_LABEL: true
    3D_OCCLUDED: true
    3D_OCCUPANCY: true
  ROOT_DIR: /root/datasets/semantic_kitti
  SPLIT:
    TEST: 3901
    TRAIN: 3834
    VAL: 815
  TYPE: SemanticKITTI
MODEL:
  TYPE: OCNet
OPTIMIZER:
  BASE_LR: 0.001
  BETA1: 0.9
  BETA2: 0.999
  MOMENTUM: NA
  TYPE: Adam
  WEIGHT_DECAY: NA
OUTPUT:
  BEST_LOSS: 0.20808246731758118
  BEST_METRIC: 0.14747651694065275
  OUTPUT_PATH: /root/OCNet/SSC_out/OCNet_SemanticKITTI_0808_214802
  OUT_ROOT: /root/OCNet/SSC_out/
SCHEDULER:
  FREQUENCY: epoch
  LR_POWER: 0.98
  TYPE: power_iteration
STATUS:
  BEST_LOSS: /root/OCNet/SSC_out/OCNet_SemanticKITTI_0808_214802/chkpt/best-loss
  BEST_METRIC: /root/OCNet/SSC_out/OCNet_SemanticKITTI_0808_214802/chkpt/best-metric
  CONFIG: /root/OCNet/SSC_out/OCNet_SemanticKITTI_0808_214802/config.yaml
  LAST: /root/OCNet/SSC_out/OCNet_SemanticKITTI_0808_214802/chkpt/last
  RESUME: true
TRAIN:
  BATCH_SIZE: 12
  CHECKPOINT_PERIOD: 15
  EPOCHS: 80
  SUMMARY_PERIOD: 50
VAL:
  BATCH_SIZE: 12
  SUMMARY_PERIOD: 20
