DATALOADER:
  NUM_WORKERS: 4
DATASET:
  AUGMENTATION:
    FLIPS: true
  MODALITIES:
    3D_LABEL: true
    3D_OCCLUDED: true
    3D_OCCUPANCY: true
  ROOT_DIR: /root/datasets/semantic_kitti
  SPLIT:
    TEST: 3901
    TRAIN: 3834
    VAL: 815
  TYPE: SemanticKITTI
MODEL:
  TYPE: OCNet
OPTIMIZER:
  LEARNING_RATE: 0.001
  NAME: Adam
  WEIGHT_DECAY: 0.0001
OUTPUT:
  BEST_LOSS: 0.22553983330726624
  BEST_METRIC: 0.12316429756958876
  OUTPUT_PATH: /root/OCNet/SSC_out/OCNet_SemanticKITTI_0806_193035
  OUT_ROOT: /root/OCNet/SSC_out/
SCHEDULER:
  FREQUENCY: epoch
  LR_POWER: 0.98
  TYPE: power_iteration
STATUS:
  BEST_LOSS: /root/OCNet/SSC_out/OCNet_SemanticKITTI_0806_193035/chkpt/best-loss
  BEST_METRIC: /root/OCNet/SSC_out/OCNet_SemanticKITTI_0806_193035/chkpt/best-metric
  CONFIG: /root/OCNet/SSC_out/OCNet_SemanticKITTI_0806_193035/config.yaml
  LAST: /root/OCNet/SSC_out/OCNet_SemanticKITTI_0806_193035/chkpt/last
  RESUME: true
TRAIN:
  BATCH_SIZE: 20
  CHECKPOINT_PERIOD: 15
  EPOCHS: 80
  SUMMARY_PERIOD: 50
VAL:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 20
